### ISSUE TITLE
testing: map one build target to multiple test targets

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1123]
The use case is that one can have only a single build and utilize it in multiple testing targets, especially such targets which cannot be built in COPR (RHEL, Oracle Enterprise Linux).

Users need to be able to say where the tests should be invoked: internally vs. externally (because tests need to access services in the internal infra)

**Comment by ZhukovGreen** [comment]
@TomasTomecek, @thrix, @psss
TMT provides a clear mapping between plans and test. So I see logically to explore how packit could map rpm to a plan. Technically we can solve this using adjust in plan definition:
```yaml
# Install the fresh pytest from pip on older distros
adjust:
    prepare+:
     - how: shell
       name: install copr build
       script: yum install copr-build-url
    when: ci-provider == packit
```

In this case, we have two problems:
1. This metadata should live in tested projects
2. Still the problem of mapping is not solved as we don't know how to map plan metadata into correct copr build.

For the 1st and 2nd  points - the solution of tft with replacing the step provisioning is better, as there is no requirements to the provisioning step defined in the testing project. What if the packaging becomes also a step and it will be replaced by packit (similar to tft). This step would demand some particular metadata that contains the information to easily map the right copr build
