### ISSUE TITLE
Enable users configure mapping between build and test targets

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1230]
The mapping between build and test targets is usually 1:1, e.g. fedora-34 -> fedora-34

But for the enterprise linux it's a bit more tricky since different distros have the same ABI (epel, centos, centos-stream, rhel, rocky, oraclelinux...). For these especially, we should have a way inside packit config to define build targets and map those to test targets, since we have 2 deployments of TF (public, internal) which offer different composes and evolve on the fly.

TODO:

- [x] propose packit config changes which would allow the 1-to-n mapping
- [x] implement 1-to-1 mapping in p-s
- [x] make sure it works properly for convert2rhel
- [ ] implement 1-to-n mapping in p-s

Context: https://github.com/packit/packit-service/pull/1225

**Comment by mfocko** [comment]
I think this becomes „a bit“ more complex once we start taking into account public **and** internal Copr (as we have spike for internal Copr in backlog too) **and also** public and internal Testing Farm instance… Ideally I would imagine some mapping via to instances via alias or hostname at least…

**Comment by TomasTomecek** [comment]
I like the structure - the 1:n mapping

would `distro_mapping` be a more descriptive name of the field? or `target[s]_mapping`

**Comment by jpopelka** [comment]
> would `distro_mapping` be a more descriptive name of the field? or `target[s]_mapping`

Prior to `targets_distros` I had `from_targets_mapping` and `target2distros_mapping`, but I removed the `mapping`, because it just means "a dictionary". We also don't have `targets_list`, but only `targets`. But yeah, I can return it back so it's more obvious what it is.

Anyone else any suggestions?

**Comment by lachmanfrantisek** [comment]
What something containing `build_to_test`?

**Comment by jpopelka** [comment]
ok, then `build_targets_to_test_distros` if that's not too long :-)

**Comment by mfocko** [comment]
I think we should be fine with `targets_distros` or `targets2distros` as long as we have it described in documentation. I would also consider an option like:

```yml
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - epel-7-x86_64
      distros: [centos-7, rhel-7]
    - epel-8-x86_64
      distros: [centos-stream-8]
    - epel-8-aarch64
  use_internal_tf: True
```

But that might be more complicated to implement…

**Comment by jpopelka** [comment]
> I think we should be fine with `targets_distros` or `targets2distros` as long as we have it described in documentation.

That's what I thought too.

> ```yaml
>     targets:
>     - epel-7-x86_64
>       distros: [centos-7, rhel-7]
> ```

Thanks, but we can't change the `targets` structure to something else than [current list of strings](https://github.com/packit/packit/blob/af3ae70ce83389a282dc77e660be0008c33d0ffc/packit/config/job_config.py#L39), since it needs to work with existing configs and `targets` is used in build job as well - that's why we need a new (`targets2distros`?) metadata field.
Anyway, if you're suggesting `targets` (or `targets2distros`) to be list of dicts, then I'm missing something, because `epel-7-x86_64` is just a value, while we need key: value.

**Comment by mfocko** [comment]
Yeah, you're right, we would need a key a for that :/

**Comment by jpopelka** [comment]
> we can't change the `targets` structure to something else than [current list of strings](https://github.com/packit/packit/blob/af3ae70ce83389a282dc77e660be0008c33d0ffc/packit/config/job_config.py#L39), since it needs to work with existing configs and `targets` is used in build job as well

But it's fine if it's "list of strings" (for backward compatibility) **OR** "something else". See packit/packit#1407
It's a bit more code because marshmallow doesn't have a "union" field, but is more user friendly:

```yaml
- job: tests
  trigger: pull_request
  metadata:
    targets:
      epel-7-x86_64:
        distros: [centos-7, rhel-7]
      epel-7-aarch64:
        distros: []
      epel-8-x86_64:
        distros: [centos-stream-8]
      epel-8-aarch64: {}
  use_internal_rf: True
```

while the old `targets: [epel-7-x86_64, epel-8-x86_64, ...]` is still valid.
