### ISSUE TITLE
Match propose_downstream configuration based on upstream release

### ISSUE THREAD

**Issue by jkonecny12** [packit/packit-service#1298]
Hi, in Anaconda we are just starting to use packit for downstream releasing and we would like to have packit a bit smarter to correctly match what release should go to which downstream branch. Our use case is that we are doing releases for every Fedora and every RHEL in the same upstream repository. The difference are branches which are used for the releases. It would be great if packit would understand this.

Our use case on https://github.com/rhinstaller/anaconda/:
master branch -> releases for Rawhide
fXX-release branches -> releases for Fedora XX
rhel-8 branch -> releases for RHEL-8
rhel-9 branch -> releases for RHEL-9

We are able to decode where should what go from version, however, we can't explain that to packit right now. So packit always creates PR to one or more branches based on the configuration.

I know that tags are not tied to branches in Git so I do not expect Packit to do it this way. However, I think some pattern matching to the tag would be interesting. My example:

```
  - job: propose_downstream
    trigger: release
    metadata:
      match_tag_template: "anaconda-36\..*"
```

Or maybe even better:

```
  - job: propose_downstream
    trigger: release
    metadata:
      match_tag_commit_header_template: "New version .* for Rawhide"
```
