### ISSUE TITLE
Allow multiple triggers for single job

### ISSUE THREAD

**Issue by jamacku** [packit/packit-service#1316]
It would be great if I could define multiple triggers for a `job`.

Currently:

```yml
jobs:
  - job: copr_build
    trigger: pull-request
    metadata:
      targets:
        - fedora-rawhide

  - job: copr_build
    trigger: release
    metadata:
      targets:
        - fedora-rawhide
```

Example of multiple triggers for job:

```yml
jobs:
  - job: copr_build
    trigger:
      - release
      - pull-request
    metadata:
      targets:
        - fedora-rawhide
```

Thank you.
