### ISSUE TITLE
Export PACKIT variables identifying repo and brach

### ISSUE THREAD

**Issue by kkaarreell** [packit/packit-service#1379]
When testing PR on Github in Packit CI, we know PACKIT_COMMIT_SHA but we do not know git repo and branch containing this commit. These should be also exported.

**Comment by lachmanfrantisek** [comment]
Thanks @kkaarreell for creating the issue.

I am checking what env. vars we set:

https://github.com/packit/packit-service/blob/56ee0595429c6577aca3933a787d9206f6f0a087/packit_service/worker/testing_farm.py#L169-L182

But only `not None` values are actually sent:
https://github.com/packit/packit-service/blob/56ee0595429c6577aca3933a787d9206f6f0a087/packit_service/worker/testing_farm.py#L184-L186

And here is an example of TF requests: https://api.dev.testing-farm.io/v0.1/requests/bef4cbfb-3928-448d-b3b5-b862f5abd8e6

And only a few are set:
```
"variables": {
    "PACKIT_COMMIT_SHA": "b1eb01629b6af035dc95d6815ca4731922fb0fa4",
    "PACKIT_DOWNSTREAM_NAME": "keylime",
    "PACKIT_DOWNSTREAM_URL": "https://src.fedoraproject.org/rpms/keylime.git",
    "PACKIT_FULL_REPO_NAME": "keylime/keylime",
    "PACKIT_PACKAGE_NAME": "keylime",
    "PACKIT_TARGET_SHA": "d85baf35f95881795cb0f9786c2a9aebdd857bcd",
    "PACKIT_UPSTREAM_NAME": "keylime",
}
```

So, @kkaarreell, you can set `upstream_project_url` to get the `PACKIT_UPSTREAM_URL` filled (for now).

But, we ideally need to:
* [ ] send the `PACKIT_UPSTREAM_URL` even if not set in the config (we know it, `self.project` can be used)
* [ ] send the branch names as `PACKIT_TARGET_BRANCH` and `PACKIT_SOURCE_BRANCH` (naming can be changed)

**Comment by lachmanfrantisek** [comment]
After some time playing with that, I'll add a few new variables that will be set only for PR jobs:

```python
{
  "PACKIT_SOURCE_SHA": self.source_branch_sha,
  "PACKIT_TARGET_SHA": self.target_branch_sha,
  "PACKIT_SOURCE_BRANCH": self.source_branch,
  "PACKIT_TARGET_BRANCH": self.target_branch,
  "PACKIT_SOURCE_URL": self.source_project_url,
  "PACKIT_TARGET_URL": self.target_project_url,
}
```

So, it will look like this:

```yaml
"variables": {
                    "PACKIT_FULL_REPO_NAME": "packit-service/hello-world",
                    "PACKIT_UPSTREAM_NAME": "hello-world",
                    "PACKIT_UPSTREAM_URL": "https://github.com/packit-service/hello-world",
                    "PACKIT_DOWNSTREAM_NAME": "hello-world",
                    "PACKIT_DOWNSTREAM_URL": "https://src.fedoraproject.org/rpms/hello-world.git",
                    "PACKIT_PACKAGE_NAME": "hello-world",
                    "PACKIT_COMMIT_SHA": "0011223344",
                    "PACKIT_SOURCE_SHA": "0011223344",
                    "PACKIT_TARGET_SHA": "deadbeef",
                    "PACKIT_SOURCE_BRANCH": "the-source-branch",
                    "PACKIT_TARGET_BRANCH": "the-target-branch",
                    "PACKIT_SOURCE_URL": "https://github.com/someone/hello-world",
                    "PACKIT_TARGET_URL": "https://github.com/packit-service/hello-world",
                },
```

Regarding the `PACKIT_UPSTREAM_URL` project, I will leave it as is for now.
