### ISSUE TITLE
Discover targets when building in users Copr repo

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#1499]
It's pretty cumbersome for users who are using their own Copr repositories to keep the list of chroots in sync with the target lists in the jobs.

This could be improved if the service could be configured to set the targets for jobs based on what chroots are enabled in the user provided Copr repo.

Something like:

```
jobs:
- job: copr_build
  trigger: release
  owner: "@cockpit"
  project: "cockpit-preview"
  targets: copr_chroots
```

Or going further: `targets` could become optional when a user provided Copr repo is used, with the default behaviour to get the list from the Copr repo.

(The example above uses the [`metadata`-less config variant](https://github.com/packit/packit/issues/1515), which is not yet released.)
