### ISSUE TITLE
Please respect `Source0:` in spec files for upstream tarballs

### ISSUE THREAD

**Issue by martinpitt** [packit/packit-service#1505]
So far we've used packit mostly for validating upstream PRs. In these cases, one always needs to specify `create-archive:`, as there is no existing tarball to download from anywhere. So it usually says something like [`make dist`](https://github.com/cockpit-project/cockpit-podman/blob/7e3e6028399bcaf307e9473384b595ac4b045da4/packit.yaml#L6)

This is different for release builds, both for `propose_upstream:` and `copr_build`: These are triggered on releases, which usually produce an official tarball and attach it as a release artifact (or use GitHub's autogenerated ones). It is quite important that distributions use the *exact* upstream tarball, for validation purposes, and avoiding subtle breakage from rebuilding them.

However, naïvely using `create-archive:` at the top does exactly that: It rebuilds the release tarball from the local git checkout instead of downloading it from upstream. As an effect, the official [cockpit-ostree-190.1.tar.xz](https://github.com/cockpit-project/cockpit-ostree/releases/tag/190.1) is *different* from the tarball in the srpm of the [packit copr_build](https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/build/4396047/).

Today I spent some time pestering @TomasTomecek and doing [some experiments](https://github.com/cockpit-project/cockpit-podman/pull/978), and Tomas pointed out that it's possible to move the `create-archive:` action to the `job: tests`:

```
  - job: tests
    trigger: pull_request
    metadata:
      targets:
      - fedora-35
      - fedora-36
      - fedora-development
      - centos-stream-9-x86_64
    actions:
      # tarball for upstream PRs
      post-upstream-clone: make cockpit-podman.spec
      create-archive: make dist
```

That then leaves the default action for all the other (release based) builds, like propose_upstream and copr_build. But I [tested that](https://github.com/cockpit-project/cockpit-podman/pull/978#discussion_r872333942), and it seems the implied default is to run

    Command: git archive --output cockpit-podman-47.3.tar.gz --prefix cockpit-podman-47.3/ HEAD

This is rather bad! For many projects it will not even work (as it's e.g. missing autoconf.sh or node_modules or any other steps that happen for the official release tarball), but the bigger problem is that for some projects it *will* work (kinda) -- but then the packages uploaded to Fedora don't use the official upstream release, but some random untested build.

IMHO it would make much more sense to respect the .spec file, and try and download its `SourceN:` tarballs. As propose-upstream/copr-build etc. are triggered on release, that's not even a race condition -- by the time the release is published, all the release artifacts should exist.

If that fails, I suggest to just fail the release -- it's better to be explicit about it than trying to cobble together *some* tarball. If you want to keep that, then can it be a fallback if `Source0:` does not work?

In https://github.com/cockpit-project/cockpit-podman/pull/978 I have a hack for this:

```yaml
actions:
  post-upstream-clone: make cockpit-podman.spec
  # tarball for releases (copr_build, koji, etc.)
  create-archive:
    - sh -exc "curl -L -O https://github.com/cockpit-project/cockpit-podman/releases/download/${PACKIT_PROJECT_VERSION}/${PACKIT_PROJECT_NAME_VERSION}.tar.xz"
    - sh -exc "ls ${PACKIT_PROJECT_NAME_VERSION}.tar.xz"
```

But this is dreadful -- it's hard to discover, hard to get right (like, missing curl's `-L` option or forgetting to wrap the thing in `sh -ex`), and duplicates information such as the download URL, which makes it harder to release from forks, for example.
