### ISSUE TITLE
Support required TF API configuration attributes

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#1534]

**Comment by r0x0d** [comment]
Thanks for the inputs, @mfocko! Your point makes sense. 

So, just to clarify better on the structure that the tests jobs should have: 

```yaml
  - job: tests
    trigger: pull_request
    identifier: tests-7to8
    metadata:
      targets:
        - fedora-36-x86_64
      fmf_url: "https://gitlab.cee.redhat.com/rolivier/leapp-packit-poc-tests"
      fmf_ref: "main"
      use_internal_tf: True
    tmt_plan_regex: "some-regex"
    environment_settings:
      provisioning: '{"post_install_script": "#!/bin/sh\nsudo sed -i s/.*ssh-rsa/ssh-rsa/ /root/.ssh/authorized_keys"}}' 
```

In the future, without the `metadata`, it would look something like this? 

```yaml 
  - job: tests
    trigger: pull_request
    identifier: tests-7to8
    targets:
      - fedora-36-x86_64
    fmf_url: "https://gitlab.cee.redhat.com/rolivier/leapp-packit-poc-tests"
    fmf_ref: "main"
    use_internal_tf: True
    tmt_plan_regex: "some-regex"
    environment_settings:
      provisioning: '{"post_install_script": "#!/bin/sh\nsudo sed -i s/.*ssh-rsa/ssh-rsa/ /root/.ssh/authorized_keys"}}'
```

Is that an acceptable structure for introducing the new parameters?

**Comment by mfocko** [comment]
You can do that already :) I do not recall which options were supported »only« in `metadata`, but as of now `metadata` are parsed just for backward-compatibility.

Regarding the new parameters, regex is fine for sure. With `provisioning` I'm not sure whether it makes sense to do something like `tf_provisioning` with nested key `post_install_script`, or just send the whole JSON-object to the TF. On one hand it is a pretty simple solution, on the other it doesn't seem that straightforward to use and is inconsistent with rest of the config.

**Comment by r0x0d** [comment]
Nice :) 

I will play a bit with both formats and see if there is any other type of settings we need to send to TF.

**Comment by r0x0d** [comment]
Hi, @mfocko. I'm applying my changes to the `JobConfig` class, and I got a question. 

Should I replicate the two parameters I want to include to the `CommonPackageConfig` as well? Or making them attributes of `JobConfig` is enough? I was trying to follow the same example you provided in the description, and at the same time, following what is done for `tmt_url`, for example. 

Diff of the two parameters being passed to the `CommonPackageConfig`

```diff
diff --git a/packit/config/job_config.py b/packit/config/job_config.py
index 06f0d6f..3f1f278 100644
--- a/packit/config/job_config.py
+++ b/packit/config/job_config.py
@@ -98,6 +98,8 @@ class JobConfig(CommonPackageConfig):
         enable_net: bool = True,
         allowed_pr_authors: Optional[List[str]] = None,
         allowed_committers: Optional[List[str]] = None,
+        tmt_plan_regex: Optional[str] = None,
+        tf_provisioning: Optional[Dict[str, Any]] = None,
     ):
         super().__init__(
             config_file_path=config_file_path,
@@ -150,6 +152,8 @@ class JobConfig(CommonPackageConfig):
             enable_net=enable_net,
             allowed_pr_authors=allowed_pr_authors,
             allowed_committers=allowed_committers,
+            tmt_plan_regex=tmt_plan_regex,
+            tf_provisioning=tf_provisioning,
         )
         self.type: JobType = type
         self.trigger: JobConfigTriggerType = trigger
@@ -203,7 +207,9 @@ class JobConfig(CommonPackageConfig):
             f"env={self.env},"
             f"enable_net={self.enable_net},"
             f"allowed_pr_authors={self.allowed_pr_authors},"
-            f"allowed_commiters={self.allowed_committers})"
+            f"allowed_commiters={self.allowed_commiters},",
+            f"tmt_plan_regex={self.tmt_plan_regex},",
+            f"tf_provisioning={self.tf_provisioning})"
         )
 
     @classmethod
@@ -263,6 +269,8 @@ class JobConfig(CommonPackageConfig):
             and self.skip_build == other.skip_build
             and self.env == other.env
             and self.enable_net == other.enable_net
+            and self.tmt_plan_regex == other.tmt_plan_regex
+            and self.tf_provisioning == other.tf_provisioning
         )
```

Diff of the two parameters being setted as an attribute of `JobConfig` class
```diff
diff --git a/packit/config/job_config.py b/packit/config/job_config.py
index 06f0d6f..24ee8b3 100644
--- a/packit/config/job_config.py
+++ b/packit/config/job_config.py
@@ -98,6 +98,8 @@ class JobConfig(CommonPackageConfig):
         enable_net: bool = True,
         allowed_pr_authors: Optional[List[str]] = None,
         allowed_committers: Optional[List[str]] = None,
+        tmt_plan_regex: Optional[str] = None,
+        tf_provisioning: Optional[Dict[str, Any]] = None,
     ):
         super().__init__(
             config_file_path=config_file_path,
@@ -153,6 +155,8 @@ class JobConfig(CommonPackageConfig):
         )
         self.type: JobType = type
         self.trigger: JobConfigTriggerType = trigger
+        self.tmt_plan_regex = tmt_plan_regex
+        self.tf_provisioning = tf_provisioning
 
     def __repr__(self):
         return (
@@ -203,7 +207,9 @@ class JobConfig(CommonPackageConfig):
             f"env={self.env},"
             f"enable_net={self.enable_net},"
             f"allowed_pr_authors={self.allowed_pr_authors},"
-            f"allowed_commiters={self.allowed_committers})"
+            f"allowed_commiters={self.allowed_commiters},",
+            f"tmt_plan_regex={self.tmt_plan_regex},",
+            f"tf_provisioning={self.tf_provisioning})"
         )
 
     @classmethod
@@ -263,6 +269,8 @@ class JobConfig(CommonPackageConfig):
             and self.skip_build == other.skip_build
             and self.env == other.env
             and self.enable_net == other.enable_net
+            and self.tmt_plan_regex == other.tmt_plan_regex
+            and self.tf_provisioning == other.tf_provisioning
         )
```

**Comment by mfocko** [comment]
I am not going to block you on that :) From the perspective of usage, I guess the regex doesn't make a lot of sense in `CommonPackageConfig`…

Smaller context: `JobConfig` specifies schema/attributes for each of the entries in `jobs`, `CommonPackageConfig` allows you to define attributes on the global level, e.g.
```yaml
tf_provisioning: «your provisioning»

jobs:
- job: tests
  identifier: my_special_tests
  tf_provisioning: «my special provision just for this job»
- job: tests
  identifier: regular_daily_grind
  # this inherits the «your provisioning»
```

I guess you can see why the regex doesn't make much sense :)
