### ISSUE TITLE
No downstream PRs created for Fedora 37 dist-git branch

### ISSUE THREAD

**Issue by thozza** [packit/packit-service#1642]
With the following configuration in [osbuild](https://github.com/osbuild/osbuild/blob/f699720dbd444c13e2c150f308216687c3eef806/.packit.yaml#L52-L56) PackIt is not creating PRs for Fedora 37 dist-git branch:
```yaml
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
      - fedora-all
```
![Screen Shot 2022-09-01 at 9 17 32](https://user-images.githubusercontent.com/3659736/187855020-fa8051d2-02d7-458c-bde6-803172c620e2.png)

f37 branches were created only recently, I guess that PackIt needs to update what `fedora-all` translates to.
