### ISSUE TITLE
Implement test -> build job referencing 

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1720]
Since it is possible to add identifiers for jobs, we allow defining multiple Copr build jobs and multiple TF jobs. In that case, Packit Service doesn't know what Copr build job to use for the particular TF job.

For this purpose, we could introduce a new field for job configs which would allow the referencing, for example:

```yaml
- job: copr_build
  identifier: "build1"
  trigger: pull_request
  actions: ...
      
- job: copr_build
  identifier: "build2"
  trigger: pull_request
  actions: ...
      
- job: tests
  identifier: "tests2"
  trigger: pull_request
  build_identifier: "build1"
      
- job: tests
  identifier: "tests2"
  trigger: pull_request
  build_identifier: "build2"
```

TODO:
- [ ] discuss the design with team (including the naming :D)
- [ ] implement 
- [ ]  properly document it
