### ISSUE TITLE
pull-from-upstream requires Packit-as-a-Service to be enabled in upstream GitHub project

### ISSUE THREAD

**Issue by nforro** [packit/packit-service#1879]
I [set up](https://src.fedoraproject.org/rpms/gpxsee/c/802c0f4a03230caba437a3f951e7cbb9122cae3f?branch=rawhide) `pull-from-upstream` for a project where upstream doesn't know anything about packit (I think that will be a common use case), using a minimalistic config:

```yaml
specfile_path: gpxsee.spec
 
upstream_package_name: GPXSee
downstream_package_name: gpxsee
 
upstream_project_url: https://github.com/tumic0/GPXSee
 
jobs:
  - job: pull_from_upstream
    trigger: release
    dist_git_branches:
      - fedora-all
```

But the job failed with: `Failed to retrieve a token: App is not installed on tumic0/GPXSee`.
I think installing the app kind of defeats the purpose of `pull-from-upstream`.

Here is coresponding Sentry issue: https://sentry.io/organizations/red-hat-it/issues/3901515095/?project=1767823
