### ISSUE TITLE
retest-failed triggers also successful test runs

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1886]
![image](https://user-images.githubusercontent.com/1662493/217184136-a6f41f32-dbd7-4a2d-89f3-07b95eaf06ef.png)

only 37 was failed, the comment triggered testing for 36 and rawhide as well

packit.yaml
```
specfile_path: ansible-bender.spec
actions:
  create-archive:
    - "python3 setup.py sdist --dist-dir ."
    - "sh -c 'echo ansible-bender-$(python3 setup.py --version).tar.gz'"
  get-current-version:
    - "python3 setup.py --version"
jobs:
- job: copr_build
  targets:
  - fedora-all
  trigger: pull_request
- job: tests
  trigger: pull_request
  targets:
  - fedora-all
- job: propose_downstream
  trigger: release
  dist_git_branches: [rawhide]
srpm_build_deps:
  - python3-pip # "python3 setup.py --version" needs it
  - python3-setuptools_scm
```
