### ISSUE TITLE
Downstream koji build issues

### ISSUE THREAD

**Issue by nforro** [packit/packit-service#1937]
I have configured packit in dist-git for https://src.fedoraproject.org/rpms/gpxsee/, with the following configuration for the `koji_build` job:

```yaml
  - job: koji_build
    trigger: commit
    allowed_pr_authors: ["packit", "nforro"]
    allowed_committers: ["nforro"]
    dist_git_branches:
      - fedora-all
```

After pushing, packit triggered builds for all branches but `f38`. I found this in the logs:
`Skipping build on 'f38'. Koji build configured only for '{'main', 'rawhide', 'f36', 'f37'}'.`

Also, `f36` build was started twice:
https://koji.fedoraproject.org/koji/taskinfo?taskID=97944069
https://koji.fedoraproject.org/koji/taskinfo?taskID=97944050
