### ISSUE TITLE
Bug: test jobs are not filtered by trigger/branch

### ISSUE THREAD

**Issue by LecrisUT** [packit/packit-service#1981]
# Why is this a bug?

Lets consider the following configuration:
```yaml
jobs:
  - job: tests
    trigger: pull_request
  - job: copr_build
    trigger: pull_request
    project: CI
  - job: tests
    trigger: commit
    branch: main
  - job: copr_build
    trigger: commit
    branch: main
    project: nightly
  - job: copr_build
    trigger: release
    project: releases
```

Here `copr_build.commit` is only triggered on branch `main` which is only intended for actual nightly releases. There you also want to check if the nightly release is functional, e.g. after a PR is merged. So far so good. Then you also have a PR workflow that pushes to a separate project so that it doesn't interfere with the nightly builds, so you also include a test job for PR, and that works all fine.

The issue appears when you combine them and you are working on the same repository and not a fork. Because `tests.commit` is not filtered by branch (or trigger apparently), it always requests a test job on pushes to e.g. `fix/issue23` (and waits indefinitely). It pollutes the commit status, but that is not the main issue. The issue is when you then do a PR. Because the `test.commit` jobs are waiting for a `copr_build.commit` which is never executed, the CI checks never finish, and if the branch is protected, you cannot merge without force.
