### ISSUE TITLE
packit.yaml: tf_extra_vars and tf_post_install_script do not play well together

### ISSUE THREAD

**Issue by thrix** [packit/packit-service#2010]
### What happened? What is the problem?

See:

https://github.com/oamg/leapp-repository/blob/7a858ee1efb9a27e3a3c5446f0dbc6bc3de810b4/.packit.yaml

Where they had:

```
  tf_post_install_script: "#!/bin/sh\nsudo sed -i s/.*ssh-rsa/ssh-rsa/ /root/.ssh/authorized_keys"
  tf_extra_params:
    environments:
      - tmt:
          context:
            distro: "rhel-7.9"
      # tag resources as sst_upgrades to enable cost metrics collection
      - settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades
```

And to the TF API this was sent:

https://api.dev.testing-farm.io/v0.1/requests/754e7bbf-a6b1-45ff-b202-3d4b18e7b9c0

```
"settings": {
  "pipeline": null,
  "provisioning": {
    "post_install_script":    "#!/bin/sh\nsudo sed -i s/.*ssh-rsa/ssh-rsa/ /root/.ssh/authorized_keys",
    "tags": null
   }
 }
},
"tmt": {
  "context": {
    "arch": "x86_64",
    "distro": "rhel-7.9",
    "trigger": "commit"
  }
},
```

Obviously, the dicts were not correctly updated in this case.

There is a simple workaround, just use tf_extra_vars, but looks like a bug

### What did you expect to happen?

`tf_extra_vars` and `tf_post_install_script` work nice together, not information is lost.

### Example URL(s)

https://github.com/oamg/leapp-repository/blob/7a858ee1efb9a27e3a3c5446f0dbc6bc3de810b4/.packit.yaml

### Steps to reproduce

```bash
1. see description
```

### What is the impacted category (job)?

Testing Farm tests

### Workaround

- [X] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [X] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by mfocko** [comment]
Just to clarify, is the config supposed to be
```yaml
  tf_post_install_script: "#!/bin/sh\nsudo sed -i s/.*ssh-rsa/ssh-rsa/ /root/.ssh/authorized_keys"
  tf_extra_params:
    environments:
      - tmt:
          context:
            distro: "rhel-7.9"
      # tag resources as sst_upgrades to enable cost metrics collection
      - settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades
```

and not
```yaml
  tf_post_install_script: "#!/bin/sh\nsudo sed -i s/.*ssh-rsa/ssh-rsa/ /root/.ssh/authorized_keys"
  tf_extra_params:
    environments:
      - tmt:
          context:
            distro: "rhel-7.9"
      # tag resources as sst_upgrades to enable cost metrics collection
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades
```
