### ISSUE TITLE
[RFE] Populate branch job attribute also for PRs

### ISSUE THREAD

**Issue by kkaarreell** [packit/packit-service#2051]
Currently, in the Packit job description one can use the `branch` attribute for `trigger: commit` to limit the scope of a job.
It would be handy to have this `branch` populated also for PRs - in this case it makes sense to me that it would contain the target branch. While one could have different `.packit.yaml` file in each branch, this feature would allow users to unify they `.packit.yaml` across branches so this file won't need an update when e.g. rewriting content of one branch with another.

Our use case:
Run different packit tests job for branch `main` containing tests and plans for an upstream project and for branch `c9s` containing plans and tests for RPM package from C9S. Once we do a rebase in C9S we update `c9s` branch with the content of the `main` branch. This feature would enable use to define packit jobs like this:
```
jobs:
- job: tests
  trigger: pull_request
  branch: main
  targets:
    - fedora-stable
    - centos-stream-9-x86_64
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "main"
- job: tests
  trigger: pull_request
  branch: c9s
  targets:
    - centos-stream-9-x86_64
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "c9s"
```
In our `tmt` plans we use the `target_PR_branch` context to enable/disable respective plans.
Once we rebase, we would basically overwrite `.packit.yaml` from `c9s` with the identical version from `main` and therefore it won't matter and require updates.
