### ISSUE TITLE
Allow sharing temporary Copr project by Monorepo packages

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#2055]
By now, when specifying multiple packages for a Copr build job, Packit creates a Copr project for each.
This might not be what people expect and might cause issues when packages are dependent.

This issue is not about resolving the dependencies. For that, we have a separate epic #1993 

Implementation options:
* A new config option to overwrite Copr project identifier.
    * Statuses will be different, Copr project name will be the same.
    * Looks like a hack from the UX perspective. This should be the default behaviour.
    * Alternatively, have a flag config option instead (to either share Copr project or ignore the identifier).
* Improve the config -> job logic to share the Copr project between the packages by default.
    * This might be tricky since the default Copr project name is resolved later.
* When resolving the default Copr project name, check the full config and realise if we are part of the same job.
    * Goes against the separation of per-package jobs and auto-identifier forwarding.

**Comment by lachmanfrantisek** [comment]
The example config:
```
  - job: copr_build
    packages:
      - python-copr
      - copr-cli
      - copr-frontend
    trigger: pull_request
    targets: fedora-37
```
