### ISSUE TITLE
Status overrides for shared Copr build

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#2058]
When the user configures a monorepo to use a shared Copr project, the build results override all the statuses.

[Example](https://github.com/fedora-copr/copr/pull/2720/commits/39c5e2c2aadee32a73e7da5058cc2072e30f41f0):

```
jobs:
  - job: copr_build
    packages:
      - python-copr
      - copr-cli
      - copr-frontend
    trigger: pull_request
    targets: fedora-37
    owner: packit
    project: copr
```

See that all statuses show the same content:

![image](https://github.com/packit/packit-service/assets/20214043/f6bda7aa-b3b4-4166-9152-78dea62eec23)
![image](https://github.com/packit/packit-service/assets/20214043/581b3481-d37e-4649-bd6e-3531c2548acf)

(Usecase with identifiers might be affected as well.)

When reacting to Copr results, we need to check (at least for the Monorepo) that the package we are working with is affected.
Probably here:
https://github.com/packit/packit-service/blob/96ef508a2a954e8dc390087eb5826e2e8b32a37b/packit_service/worker/events/copr.py#L66
