### ISSUE TITLE
Incorrect reporting for tests when retriggering a build of different target that is not configured for tests

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#2119]
With a configuration like this:
```yaml
    -  job: copr_build
      trigger: pull_request
      targets:
          - fedora-rawhide-x86_64
          - epel-8-x86_64

    - job: tests
      trigger: pull_request
      targets:
        - epel-8-x86_64
```

when one retriggers the `fedora-rawhide-x86_64` build, the status of the SRPM build will be reported for the test job as well, resulting in this case in a `testing-farm:centos-stream-8-x86_64` status pending indefinitely with `SRPM build succeeded. Waiting for RPM build to start...` message. 

This happened in https://github.com/openscanhub/openscanhub/pull/44/.
