### ISSUE TITLE
Copr build jobs with different identifiers don't seem to honor configured targets

### ISSUE THREAD

**Issue by nforro** [packit/packit-service#2131]
Consider the following config:

```yaml
  - job: copr_build
    trigger: pull_request
    identifier: fedora-and-epel
    targets:
      - fedora-all
      - epel-9
  - job: copr_build
    trigger: pull_request
    specfile_path: epel8/python-specfile.spec
    identifier: epel8
    actions:
      create-archive:
        - python3 setup.py sdist --dist-dir ./epel8/
        - bash -c "ls -1t ./epel8/*.tar.gz | head -n 1"
      get-current-version: python3 setup.py --version
      pre-sync:
        - python3 plans/git_reference.py
    targets:
      - epel-8

  - job: tests
    trigger: pull_request
    identifier: fedora-and-epel
    targets:
      - fedora-all
      - epel-9

  - job: tests
    trigger: pull_request
    identifier: epel8
    targets:
      - epel-8
```

I would expect only two `copr_build` jobs with `epel8` suffix and no job with `epel-8-x86_64` chroot and `fedora-and-epel` suffix, but this is the job list (test jobs seem to work fine):

![jobs](https://github.com/packit/packit-service/assets/14923067/38a3f18d-2bdf-4129-898d-feb8c51ec953)

Here is a draft PR to demonstrate the issue: https://github.com/packit/specfile/pull/257
