### ISSUE TITLE
Koji builds not triggered

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#2206]
In dist-git, I merged a [PR which adds `.packit.yaml`](https://src.fedoraproject.org/rpms/rpmdeplint/pull-request/15#request_diff) with

```yaml
- job: koji_build
  trigger: commit
  dist_git_branches:
   - fedora-all
   - epel-9
```

I was expecting to see some builds in [Koji](https://koji.fedoraproject.org/koji/packageinfo?packageID=23204) but none has been triggered.

The PR was created by me, but I amended Packit's commit as instructed in [the original PR](https://src.fedoraproject.org/rpms/rpmdeplint/pull-request/13) because I needed some tweaks.
