### ISSUE TITLE
Implement a `label_trigger` option for test jobs

### ISSUE THREAD

**Issue by psss** [packit/packit-service#2269]
### Description

Similar to `manual_trigger` the `label_trigger` would enable specific test job only if given label is attached to the pull request.

### Benefit

Once the pull request has passed basic sanity tests or an agreed level of code review, it would be marked for example with a `full test` label and all future pull request changes would be tested without need to again and again manually add `/packit test --identifier full` comments. Also this would resolve the problem with having to wait until the copr builds are ready, see #2265 for details.

### Importance

This would substantially improve the several-tier-testing experience. And prevent unnecessary manual steps.

### What is the impacted category (job)?

Testing Farm tests

### Workaround

- [X] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by psss** [comment]
As @lachmanfrantisek mentioned on the chat, this should behave like a condition (during the job scheduling the label would be just checked for presence) rather than a trigger (like watching the event when the label was added), so maybe the proposed option name is a bit misleading.

**Comment by psss** [comment]
Is there any ETA on implementing this?

**Comment by lbarcziova** [comment]
hi @psss, I have put this to `ready-to-refine`, so I hope we could get to this in the next 2-3 weeks.

**Comment by psss** [comment]
Great, thanks for the update!

**Comment by majamassarini** [comment]
If possible also check for labels to not be present. Think about one implementation that can be reused in more jobs.

**Comment by mfocko** [comment]
With regards to the last comment, I would suggest something like:
```yaml
label_trigger:
  present:
    - test_regressions
  absent:
    - skip_tests
    - ci_skip
```

To clarify what we discussed during the refinement, we also considered being able to run jobs **only** if there are labels missing, the example above probably explains it well.

**Comment by psss** [comment]
Negative filter sounds useful. The proposed syntax looks good. Perhaps, one more brainstorming idea: What about this?

```yaml
trigger:
    label:
        present:
          - test_regressions
        absent:
          - skip_tests
          - ci_skip
```

**Comment by mfocko** [comment]
Did you have something like
```yaml
trigger:
    label:
        present:
          - test_regressions
        absent:
          - skip_tests
          - ci_skip
    manual: true
```

in mind? With `manual_trigger` as backwards-compatible and to-be-deprecated it sounds pretty reasonable :thinking:

**Comment by psss** [comment]
Yeah, that was the idea, to group all triggers under a single `trigger` umbrella.

**Comment by psss** [comment]
> rather than a trigger (like watching the event when the label was added)

Maybe it would be good to clarify the expected behavior first: What will happen if a new label is added to the pull request and there are jobs (marked with that label) already waiting in the queue? I'd say it would be nice if the missing jobs are started right away.

**Comment by lbarcziova** [comment]
From your comment and also checking [the thread](https://redhat-internal.slack.com/archives/C04MU29TES1/p1701869253292439) on Slack, I think we agreed it would behave only like a condition, so adding/removing a label would not trigger Packit's action.

**Comment by psss** [comment]
Ok, so it should behave only as a condition. Do we expect there will/could be other conditions? If so, the following would be a bit more extensible syntax:

```yaml
condition:
    label:
        present:
          - test_regressions
        absent:
          - skip_tests
          - ci_skip
```

Single key `labels` would collide with [packit job labels](https://packit.dev/posts/manual-triggering#triggering-test-jobs-based-on-labels-and-identifiers), or not?
