### ISSUE TITLE
Support mixed sources

### ISSUE THREAD

**Issue by xsuchy** [packit/packit-service#2314]
The spec file `rubygem-cucumber-gherkin.spec` contains:

```
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem
# git clone --no-checkout https://github.com/cucumber/gherkin-ruby
# git -C gherkin-ruby archive -v -o rubygem-gherkin-22.0.0-testdata.txz v22.0.0 testdata/
Source1: %{name}-%{version}-testdata.txz
```
I tried to create packit.yaml https://src.fedoraproject.org/rpms/rubygem-cucumber-gherkin/pull-request/2#request_diff

but it creates
https://src.fedoraproject.org/rpms/rubygem-cucumber-gherkin/pull-request/3#request_diff

I did not find a way how to tell Packit to download and update Source0 and at the same time using actions generate and update Source1.

**Comment by nforro** [comment]
I think it would make sense to make `create-archive` available also in sync release workflow, and to add an e.g. `source` option:

```yaml
actions:
  create-archive:
    source: 1
    script:     
      - git archive -o tests-${PACKIT_PROJECT_VERSION}.tar.xz tests/
      - bash -c "echo tests-${PACKIT_PROJECT_VERSION}.tar.xz"
```
