### ISSUE TITLE
[RFC] Parametrized Copr builds

### ISSUE THREAD

**Issue by mrc0mmand** [packit/packit-service#2610]
Hey!

While using Packit in various upstream projects a one potentially useful feature came to mind that's (AFAIK) currently not possible with Packit: do multiple Copr builds with different parameters and run the same tests on all such builds.

The main use case (from my side) is to do both a regular build and a _sanitized_ build (using [ASan](https://clang.llvm.org/docs/AddressSanitizer.html)/[UBSan](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html)/etc.) in a single PR and then execute the same set of tests on both builds.

The easiest way I could think of right now would be probably allowing passing custom arguments to `rpmbuild` (if that's even possible from Packit's side), i.e. something like:

```yaml
jobs:
- job: copr_build
  trigger: pull_request
  rpmbuild_params: --define "sanitized_build 1"
  targets:
    - fedora-stable
    - centos-stream-8-x86_64
```

Where the respective spec file would need to be adjusted to account for the just defined option (or maybe even something like `--define "build_cflags %{__build_flags_lang_c} %{?_distro_extra_cflags} -fsanitize=address,undefined"` would do, which wouldn't require spec file modifications, but it's way less obvious. But that's just an initial idea, there's probably a better way to achieve this.

Would something like this make sense in Packit or be even possible?

(/cc @evverx)
