### ISSUE TITLE
Too many copr builds triggered when tests jobs are defined

### ISSUE THREAD

**Issue by majamassarini** [packit/packit-service#2669]
Working on re-triggering of failed tests, I realized we are triggering non needed copr builds.

```
jobs:
- job: copr_build
  trigger: pull_request
  identifier: latest
  targets:
  - fedora-latest-x86_64

- job: copr_build
  trigger: pull_request
  targets:
  - fedora-rawhide-x86_64
```
The above snippet is taken from [this PR](https://github.com/packit/hello-world/pull/2119); one copr build for `rawhide` and one for `f41` with `latest` identifier should be enough, instead we are triggering even the `rawhide` build in the copr repo with `latest` identifier and  the `f41` build in the copr repo with no identifier.
This is caused by the definition of tests jobs (not listed in the snippet) for which we are looking in all defined targets:

https://github.com/packit/packit-service/blob/d6b6a6e5fc8e934ed3d71444e0b82fc8e980df42/packit_service/worker/helpers/build/build_helper.py#L94-L96

**There are no issues for any user but we are wasting resources.**

---

There is also another issue related with the wrong `build_targets` count.

https://github.com/packit/packit-service/blob/d6b6a6e5fc8e934ed3d71444e0b82fc8e980df42/packit_service/worker/jobs.py#L359-L360

**We are submitting the wrong number of build_targets (for too many times) to the pushgateway.**
When there are multiple copr jobs defined and there is also at least one test job defined, we are submitting for every copr job and every test job the sum of all defined targets (since the CoprBuildJobHelper is initialized even for the tests jobs).
I think this is the cause of our wrong metrics #2430 (we have many more queued tasks than started or finished).
