### ISSUE TITLE
Downstream release proposal does not respect requested dist-git branches

### ISSUE THREAD

**Issue by bocekm** [packit/packit-service#624]
[The packit conf for convert2rhel](https://github.com/oamg/convert2rhel/blob/master/.packit.yaml) says that the dist-git branches to be used for downstream release are `el6` and `epel7`:
```
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
    - el6
    - epel7
```

Yet, after creating [a new upstream release](https://github.com/oamg/convert2rhel/releases/tag/v0.11), packit has created a downstream PR only for the `master` dist-git branch (which is used for Fedora Rawhide): https://src.fedoraproject.org/rpms/convert2rhel/pull-request/2.
