### ISSUE TITLE
only one job executed for 2 build definitations for the same trigger

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#755]
```yaml
---                                                                                                                                                                          
specfile_path: hello.spec                                                                                                                                                    
synced_files:                                                                                                                                                                
  - hello.spec                                                                                                                                                               
upstream_package_name: hello                                                                                                                                                 
downstream_package_name: hello                                                                                                                                               
jobs:                                                                                                                                                                        
- job: copr_build                                                                                                                                                            
  trigger: pull_request                                                                                                                                                      
  metadata:                                                                                                                                                                  
    targets:                                                                                                                                                                 
    - fedora-rawhide-x86_64                                                                                                                                                  
  actions:                                                                                                                                                                   
    post-upstream-clone: "ls /*"                                                                                                                                             
- job: copr_build                                                                                                                                                            
  trigger: pull_request                                                                                                                                                      
  metadata:                                                                                                                                                                  
    targets:                                                                                                                                                                 
    - fedora-32-x86_64                                                                                                                                                       
  actions:                                                                                                                                                                   
    post-upstream-clone: 'bash -c "ls /*"'   
```

And I only got:
```
packit-stg/rpm-build-fedora-rawhide-x86_64 — SRPM build failed, check the logs for details. 
```
no F32
