### ISSUE TITLE
Integrate FMF relevancy with our test targets

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#839]
Context: https://github.com/psss/tmt/issues/101#issuecomment-694730292

FMF/TMT enables people to join plans with target environments and run plans conditionally - it would be nice if people were able to specify these selectors in packit.yaml for particular targets.

The concrete use case is: if the target env is X, run these plans - the main problem here is python2/3 - install specific packages based on the python version.

**Comment by thrix** [comment]
It is not yet clear if any packit integration in the config file will be needed. Testing Farm will specify the environment on which the tests are being run, and the plans can be relevant to the given environment or not, according to that they will be executed (or skipped).

**Comment by TomasTomecek** [comment]
oki, so let's keep this open in the meantime and when the feature is ready in tmt, we can discuss if there is anything needed to be done on our side

**Comment by lachmanfrantisek** [comment]
Looks like the fmf/tmt part is already done. What can we do here on our side, @psss ?

**Comment by psss** [comment]
Once the testing farm api [support for providing context](https://gitlab.com/testing-farm/api/-/issues/2) is implemented, packit should just provide the right context when scheduling a new job. It will be something like this:

    distro: fedora-33
    arch: x86_64
    trigger: code

See the tmt [context](https://tmt.readthedocs.io/en/latest/spec/context.html) docs for more info about the context definition.

**Comment by lachmanfrantisek** [comment]
@psss Does it need it to be configurable by users? Or, can we guess the `distro` and `arch` from the target and use `trigger: code`?

**Comment by psss** [comment]
Packit should auto-detect these values. Users can freely define context when running tests locally or they can store their defaults in [plan context](https://tmt.readthedocs.io/en/latest/spec/plans.html#context). There should be no need to make this configurable in packit.

**Comment by lachmanfrantisek** [comment]
Ok, so not much (if any) work on our side if I get that correctly.

**Comment by psss** [comment]
Yeah, basically just preparing a simple `yaml` file with the context and passing it through the testing farm api.

**Comment by psss** [comment]
Support for the context setting is now available in the Testing Farm API. Here's an example request which includes the context:

```yaml
{
    "api_key": "****",
    "test": {
        "fmf": {
            "url": "https://src.fedoraproject.org/forks/psss/rpms/tmt",
            "ref": "53df3869e03386dcc2e2fef381588a44d4aa1387"
        }
    },
    "environments": [
        {
            "arch": "x86_64",
            "os": {
                "compose": "Fedora-32"
            },
            "artifacts": [
                {
                    "id": "62189455",
                    "type": "fedora-koji-build"
                }
            ],
            "tmt": {
                "context": {
                    "distro": "fedora-32",
                    "arch": "x86_64",
                    "trigger": "commit"
                }
            }
        }
    ]
}
```

Please, use `commit` as the trigger type. Thanks.
