### ISSUE TITLE
Reference test repository in the test job metadata

### ISSUE THREAD

**Issue by mrc0mmand** [packit/packit-service#968]
Hello!

Would it be possible to use the test job metadata to reference a repository which contains the whole FMF tree with tests to run? Something along these lines:

```yaml
    jobs:
    - job: tests
      trigger: pull_request
      metadata:
        targets:
        - fedora-all
        repo_url: "https://github.com/johnsmith/my-fabulous-tests"
```

I know that currently you can reference a test repository [using FMF](https://packit.dev/docs/testing-farm/#systemd-tests), but even for this you need to have an initialized FMF tree in the repo plus the respective FMF file. Being able to reference the test repo directly in `packit.yml` would be way nicer, imo.

I'm not sure if this RFE should be filed for Packit or TMT/TFT, so apologies if I chose the *wrong* project :-)

**Comment by csomh** [comment]
Hey @mrc0mmand :wave: 

This is definately the _right_ project to file this issue and this is a good proposal. Let's see what the others say, but I'm all for implementing this... and shouldn't be that difficult either.

**Comment by jpopelka** [comment]
I'd call it `fmf_url` and optional `fmf_ref`, but yes, makes sense.
```yaml
    jobs:
    - job: tests
      trigger: pull_request
      metadata:
        targets:
          - fedora-all
        fmf_url: https://github.com/johnsmith/my-fabulous-tests
        fmf_ref: main  # optional, defaults to repo's default branch
```

It should be as easy as putting this [into TF request payload instead of the source repo url/ref](https://github.com/packit/packit-service/blob/d12836284f5e34f54dc6de20279175493b5f5d31/packit_service/worker/testing_farm.py#L77).
